import { Stack, Text, Box } from '@chakra-ui/react'

export const Dashboard = () => (
  <Stack
    paddingX="40px"
    justify="flex-start"
    align="center"
    spacing="36px"
    background="#FFFFFF"
  >
    <Stack
      justify="flex-start"
      align="flex-start"
      spacing="42px"
      alignSelf="stretch"
    >
      <Stack
        direction="row"
        justify="space-between"
        align="center"
        spacing="683px"
        alignSelf="stretch"
      >
        <Text
          fontFamily="Zilla Slab"
          lineHeight="1.14"
          fontWeight="bold"
          fontSize="42px"
          letterSpacing="0.02em"
          textTransform="uppercase"
          color="#534C46"
        >
          Dashboard
        </Text>
        <Stack
          direction="row"
          justify="flex-end"
          align="flex-start"
          spacing="16px"
        >
          <Stack
            paddingX="24px"
            active="Default"
            height="40px"
            direction="row"
            justify="center"
            align="center"
            overflow="hidden"
            borderColor="#534C46"
            borderStartWidth="2px"
            borderEndWidth="2px"
            borderTopWidth="2px"
            borderBottomWidth="2px"
          >
            <Text
              fontFamily="Outfit"
              lineHeight="1.11"
              fontWeight="semibold"
              fontSize="18px"
              color="#534C46"
              textAlign="center"
            >
              Submit Sales Report
            </Text>
          </Stack>
          <Stack
            paddingX="24px"
            active="Default"
            height="40px"
            direction="row"
            justify="center"
            align="center"
            overflow="hidden"
            borderColor="#534C46"
            borderStartWidth="2px"
            borderEndWidth="2px"
            borderTopWidth="2px"
            borderBottomWidth="2px"
          >
            <Text
              fontFamily="Outfit"
              lineHeight="1.11"
              fontWeight="semibold"
              fontSize="18px"
              color="#534C46"
              textAlign="center"
            >
              Apply to Markets
            </Text>
          </Stack>
        </Stack>
      </Stack>
      <Stack
        justify="flex-start"
        align="flex-start"
        spacing="1px"
        alignSelf="stretch"
      >
        <Stack
          padding="24px"
          borderBottomRadius="8px"
          direction="row"
          justify="flex-start"
          align="flex-start"
          spacing="24px"
          borderColor="#60A29B"
          borderStartWidth="2px"
          borderEndWidth="2px"
          borderBottomWidth="2px"
          alignSelf="stretch"
          background="#EFF6F5"
        >
          <Text
            fontFamily="Outfit"
            lineHeight="1.33"
            fontWeight="regular"
            fontSize="24px"
            color="#000000"
            flex="1"
          >
            Pleitez Produce is in good standing [explanation about standing
            status]{' '}
          </Text>
          <Stack
            padding="8px"
            property1="Default"
            direction="row"
            justify="center"
            align="flex-start"
            borderColor="#FFFFFF"
            borderStartWidth="2px"
            borderEndWidth="2px"
            borderTopWidth="2px"
            borderBottomWidth="2px"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#FFFFFF"
              >
                good
              </Text>
            </Stack>
          </Stack>
        </Stack>
      </Stack>
    </Stack>
    <Stack
      direction="row"
      justify="flex-start"
      align="flex-start"
      spacing="24px"
      alignSelf="stretch"
    >
      <Stack
        padding="16px"
        borderRadius="8px"
        justify="flex-start"
        align="flex-start"
        borderColor="#5DA29A"
        borderStartWidth="2px"
        borderEndWidth="2px"
        borderTopWidth="2px"
        borderBottomWidth="2px"
        alignSelf="stretch"
        background="#F6F5F4"
      >
        <Stack
          paddingBottom="8px"
          width="404px"
          maxWidth="100%"
          direction="row"
          justify="flex-start"
          align="flex-start"
        >
          <Stack width="24px" height="24px" />
          <Text
            fontFamily="Zilla Slab"
            lineHeight="1"
            fontWeight="semibold"
            fontSize="24px"
            letterSpacing="0.03em"
            textTransform="capitalize"
            color="#534C46"
            flex="1"
          >
            My Upcoming Markets
          </Text>
        </Stack>
        <Text
          fontFamily="Outfit"
          lineHeight="1.6"
          fontWeight="semibold"
          fontSize="10px"
          textTransform="uppercase"
          textDecoration="underline"
          color="#000000"
          alignSelf="stretch"
          textAlign="end"
        >
          Market Date
        </Text>
        <Stack justify="flex-start" align="flex-start" spacing="16px">
          <Stack
            paddingY="4px"
            property1="Default"
            width="404px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Columbia Heights [Saturday]
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              12/10/22
            </Text>
          </Stack>
          <Stack
            paddingY="4px"
            property1="Default"
            width="404px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Monroe St.
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              12/10/22
            </Text>
          </Stack>
          <Stack
            paddingY="4px"
            property1="Default"
            width="404px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Columbia Heights [Wednesday]
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              12/14/22
            </Text>
          </Stack>
          <Stack
            paddingY="4px"
            property1="Default"
            width="404px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Columbia Heights [Saturday]
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              12/17/22
            </Text>
          </Stack>
          <Stack
            paddingY="4px"
            property1="Default"
            width="404px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Monroe St.
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              12/17/22
            </Text>
          </Stack>
        </Stack>
      </Stack>
      <Stack
        padding="16px"
        borderRadius="8px"
        justify="flex-start"
        align="flex-start"
        borderColor="#5DA29A"
        borderStartWidth="2px"
        borderEndWidth="2px"
        borderTopWidth="2px"
        borderBottomWidth="2px"
        flex="1"
        alignSelf="stretch"
        background="#F6F5F4"
      >
        <Stack
          paddingBottom="8px"
          width="404px"
          maxWidth="100%"
          direction="row"
          justify="flex-start"
          align="flex-start"
        >
          <Stack width="24px" height="24px" />
          <Text
            fontFamily="Zilla Slab"
            lineHeight="1"
            fontWeight="semibold"
            fontSize="24px"
            letterSpacing="0.03em"
            textTransform="capitalize"
            color="#534C46"
            flex="1"
          >
            Sales Reports Due
          </Text>
        </Stack>
        <Text
          fontFamily="Outfit"
          lineHeight="1.6"
          fontWeight="semibold"
          fontSize="10px"
          textTransform="uppercase"
          textDecoration="underline"
          color="#000000"
          alignSelf="stretch"
          textAlign="end"
        >
          Due By
        </Text>
        <Stack justify="flex-start" align="flex-start" spacing="16px">
          <Stack
            paddingY="4px"
            property1="Default"
            width="404.71px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Columbia Heights [Saturday]
              </Text>
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="regular"
                fontSize="14px"
                color="#595959"
              >
                <span>o</span>
                <Box as="span" textTransform="capitalize">
                  n 11/26/22
                </Box>
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              {' '}
              11/29/22
            </Text>
          </Stack>
          <Stack
            paddingY="4px"
            property1="Default"
            width="404.71px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Monroe St.
              </Text>
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="regular"
                fontSize="14px"
                color="#595959"
              >
                <span>o</span>
                <Box as="span" textTransform="capitalize">
                  n 11/26/22
                </Box>
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              {' '}
              11/29/22
            </Text>
          </Stack>
          <Stack
            paddingY="4px"
            property1="Default"
            width="404.71px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Columbia Heights [Wednesday]
              </Text>
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="regular"
                fontSize="14px"
                color="#595959"
              >
                <span>o</span>
                <Box as="span" textTransform="capitalize">
                  n 11/30/22
                </Box>
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              {' '}
              12/6/22
            </Text>
          </Stack>
          <Stack
            paddingY="4px"
            property1="Default"
            width="404.71px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Columbia Heights [Saturday]
              </Text>
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="regular"
                fontSize="14px"
                color="#595959"
              >
                <span>o</span>
                <Box as="span" textTransform="capitalize">
                  n 12/3/22
                </Box>
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              {' '}
              12/6/22
            </Text>
          </Stack>
          <Stack
            paddingY="4px"
            property1="Default"
            width="404.71px"
            maxWidth="100%"
            direction="row"
            justify="flex-start"
            align="center"
          >
            <Stack
              direction="row"
              justify="center"
              align="flex-start"
              spacing="4px"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="semibold"
                fontSize="14px"
                textTransform="capitalize"
                color="#000000"
              >
                Columbia Heights [Wednesday]
              </Text>
              <Text
                fontFamily="Outfit"
                lineHeight="1.14"
                fontWeight="regular"
                fontSize="14px"
                color="#595959"
              >
                <span>o</span>
                <Box as="span" textTransform="capitalize">
                  n 12/7/22
                </Box>
              </Text>
            </Stack>
            <span className="unsupported" />
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
              textAlign="end"
            >
              {' '}
              12/13/22
            </Text>
          </Stack>
        </Stack>
      </Stack>
      <Stack
        padding="16px"
        borderRadius="8px"
        justify="flex-start"
        align="flex-start"
        borderColor="#5DA29A"
        borderStartWidth="2px"
        borderEndWidth="2px"
        borderTopWidth="2px"
        borderBottomWidth="2px"
        alignSelf="stretch"
        background="#F6F5F4"
      >
        <Stack
          paddingBottom="8px"
          width="404px"
          maxWidth="100%"
          direction="row"
          justify="flex-start"
          align="flex-start"
        >
          <Stack width="24px" height="24px" />
          <Text
            fontFamily="Zilla Slab"
            lineHeight="1"
            fontWeight="semibold"
            fontSize="24px"
            letterSpacing="0.03em"
            textTransform="capitalize"
            color="#534C46"
            flex="1"
          >
            Sales Reports Submitted
          </Text>
        </Stack>
        <Text
          fontFamily="Proxima Nova"
          lineHeight="1.6"
          fontWeight="semibold"
          fontSize="10px"
          textTransform="uppercase"
          textDecoration="underline"
          color="#000000"
          alignSelf="stretch"
          textAlign="end"
        >
          Status
        </Text>
        <Stack
          paddingY="4px"
          property1="Default"
          alignSelf="stretch"
          direction="row"
          justify="flex-start"
          align="center"
        >
          <Stack
            direction="row"
            justify="center"
            align="flex-start"
            spacing="4px"
          >
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="semibold"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
            >
              Columbia Heights [Saturday]
            </Text>
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              color="#595959"
            >
              <span>o</span>
              <Box as="span" textTransform="capitalize">
                n 11/19/22
              </Box>
            </Text>
            <Stack property1="Default" width="10px" height="10px">
              <Stack width="10px" height="10px" />
            </Stack>
          </Stack>
          <span className="unsupported" />
          <Stack
            showArrow
            context
            label="Message"
            showContext
            state="Default"
            dark={false}
            direction="row"
            justify="center"
            align="center"
            spacing="0px"
            overflow="hidden"
          >
            <Stack justify="center" align="flex-start" spacing="0px">
              <Stack
                borderRadius="2000px"
                direction="row"
                justify="center"
                align="center"
                spacing="0px"
                background="white"
              >
                <Stack width="24px" height="24px" />
              </Stack>
            </Stack>
          </Stack>
        </Stack>
        <Stack
          paddingY="4px"
          property1="Default"
          alignSelf="stretch"
          direction="row"
          justify="flex-start"
          align="center"
        >
          <Stack
            direction="row"
            justify="center"
            align="flex-start"
            spacing="4px"
          >
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="semibold"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
            >
              Monroe St.
            </Text>
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              color="#595959"
            >
              <span>o</span>
              <Box as="span" textTransform="capitalize">
                n 11/19/22
              </Box>
            </Text>
            <Stack property1="Default" width="10px" height="10px">
              <Stack width="10px" height="10px" />
            </Stack>
          </Stack>
          <span className="unsupported" />
          <Stack
            showArrow
            context
            label="Message"
            showContext
            state="Default"
            dark={false}
            direction="row"
            justify="center"
            align="center"
            spacing="0px"
            overflow="hidden"
          >
            <Stack justify="center" align="flex-start" spacing="0px">
              <Stack
                borderRadius="2000px"
                direction="row"
                justify="center"
                align="center"
                spacing="0px"
                background="white"
              >
                <Stack width="24px" height="24px" />
              </Stack>
            </Stack>
          </Stack>
        </Stack>
        <Stack
          paddingY="4px"
          property1="Default"
          alignSelf="stretch"
          direction="row"
          justify="flex-start"
          align="center"
        >
          <Stack
            direction="row"
            justify="center"
            align="flex-start"
            spacing="4px"
          >
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="semibold"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
            >
              Columbia Heights [Wednesday]
            </Text>
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              color="#595959"
            >
              <span>o</span>
              <Box as="span" textTransform="capitalize">
                n 11/16/22
              </Box>
            </Text>
            <Stack property1="Default" width="10px" height="10px">
              <Stack width="10px" height="10px" />
            </Stack>
          </Stack>
          <span className="unsupported" />
          <Stack
            showArrow
            context
            label="Message"
            showContext
            state="Default"
            dark={false}
            direction="row"
            justify="center"
            align="center"
            spacing="0px"
            overflow="hidden"
          >
            <Stack justify="center" align="flex-start" spacing="0px">
              <Stack
                borderRadius="2000px"
                direction="row"
                justify="center"
                align="center"
                spacing="0px"
                background="white"
              >
                <Stack width="24px" height="24px" />
              </Stack>
            </Stack>
          </Stack>
        </Stack>
        <Stack
          paddingY="4px"
          property1="Default"
          alignSelf="stretch"
          direction="row"
          justify="flex-start"
          align="center"
        >
          <Stack
            direction="row"
            justify="center"
            align="flex-start"
            spacing="4px"
          >
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="semibold"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
            >
              Columbia Heights [Saturday]
            </Text>
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              color="#595959"
            >
              <span>o</span>
              <Box as="span" textTransform="capitalize">
                n 11/12/22
              </Box>
            </Text>
            <Stack property1="Default" width="10px" height="10px">
              <Stack width="10px" height="10px" />
            </Stack>
          </Stack>
          <span className="unsupported" />
          <Stack
            showArrow
            context
            label="Message"
            showContext
            state="fail"
            dark={false}
            direction="row"
            justify="center"
            align="center"
            spacing="0px"
            overflow="hidden"
          >
            <Stack justify="center" align="flex-start" spacing="0px">
              <Stack
                borderRadius="2000px"
                direction="row"
                justify="center"
                align="center"
                spacing="0px"
                background="#E35B31"
              >
                <Stack width="24px" height="24px" />
              </Stack>
            </Stack>
          </Stack>
        </Stack>
        <Stack
          paddingY="4px"
          property1="Default"
          alignSelf="stretch"
          direction="row"
          justify="flex-start"
          align="center"
        >
          <Stack
            direction="row"
            justify="center"
            align="flex-start"
            spacing="4px"
          >
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="semibold"
              fontSize="14px"
              textTransform="capitalize"
              color="#000000"
            >
              Monroe St.
            </Text>
            <Text
              fontFamily="Outfit"
              lineHeight="1.14"
              fontWeight="regular"
              fontSize="14px"
              color="#595959"
            >
              <span>o</span>
              <Box as="span" textTransform="capitalize">
                n 11/12/22
              </Box>
            </Text>
            <Stack property1="Default" width="10px" height="10px">
              <Stack width="10px" height="10px" />
            </Stack>
          </Stack>
          <span className="unsupported" />
          <Stack
            showArrow
            context
            label="Message"
            showContext
            state="Success"
            dark={false}
            direction="row"
            justify="center"
            align="center"
            spacing="0px"
            overflow="hidden"
          >
            <Stack justify="center" align="flex-start" spacing="0px">
              <Stack
                borderRadius="2000px"
                direction="row"
                justify="center"
                align="center"
                spacing="0px"
                height="24px"
                background="#60A29B"
              >
                <Stack width="24px" height="24px" />
              </Stack>
            </Stack>
          </Stack>
        </Stack>
      </Stack>
    </Stack>
    <Stack
      justify="flex-start"
      align="flex-start"
      spacing="32px"
      alignSelf="stretch"
    >
      <Stack
        direction="row"
        justify="flex-start"
        align="center"
        spacing="24px"
        alignSelf="stretch"
      >
        <Text
          fontFamily="Outfit"
          lineHeight="1"
          fontWeight="black"
          fontSize="24px"
          textTransform="uppercase"
          color="#534C46"
        >
          Season to date{' '}
        </Text>
      </Stack>
      <Stack
        direction="row"
        justify="space-between"
        align="center"
        spacing="97px"
        alignSelf="stretch"
      >
        <Stack
          padding="8px"
          property1="Default"
          justify="flex-start"
          align="center"
        >
          <Stack direction="row" justify="center" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1"
              fontWeight="medium"
              fontSize="64px"
              textTransform="uppercase"
              color="#534C46"
            >
              $320,776
            </Text>
          </Stack>
          <Text
            fontFamily="Zilla Slab"
            lineHeight="1"
            fontWeight="bold"
            fontSize="24px"
            textTransform="uppercase"
            color="#4959A8"
            textAlign="center"
          >
            Total sales
          </Text>
        </Stack>
        <Stack
          padding="8px"
          property1="Default"
          justify="flex-start"
          align="center"
        >
          <Stack direction="row" justify="center" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1"
              fontWeight="medium"
              fontSize="64px"
              textTransform="uppercase"
              color="#534C46"
            >
              118
            </Text>
          </Stack>
          <Text
            fontFamily="Zilla Slab"
            lineHeight="1"
            fontWeight="bold"
            fontSize="24px"
            textTransform="uppercase"
            color="#4959A8"
            textAlign="center"
          >
            Days at Markets
          </Text>
        </Stack>
        <Stack
          padding="8px"
          property1="Default"
          justify="flex-start"
          align="center"
        >
          <Stack direction="row" justify="center" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1"
              fontWeight="medium"
              fontSize="64px"
              textTransform="uppercase"
              color="#534C46"
            >
              4
            </Text>
          </Stack>
          <Text
            fontFamily="Zilla Slab"
            lineHeight="1"
            fontWeight="bold"
            fontSize="24px"
            textTransform="uppercase"
            color="#4959A8"
            textAlign="center"
          >
            unjustified absences
          </Text>
        </Stack>
        <Stack
          padding="8px"
          property1="Default"
          justify="flex-start"
          align="center"
        >
          <Stack direction="row" justify="center" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1"
              fontWeight="medium"
              fontSize="64px"
              textTransform="uppercase"
              color="#534C46"
            >
              $16,903
            </Text>
          </Stack>
          <Text
            fontFamily="Zilla Slab"
            lineHeight="1"
            fontWeight="bold"
            fontSize="24px"
            textTransform="uppercase"
            color="#4959A8"
            textAlign="center"
          >
            Gross Market Fees
          </Text>
        </Stack>
      </Stack>
    </Stack>
    <Stack
      padding="32px"
      borderRadius="8px"
      justify="flex-start"
      align="center"
      spacing="24px"
      borderColor="#6D635B"
      borderStartWidth="2px"
      borderEndWidth="2px"
      borderTopWidth="2px"
      borderBottomWidth="2px"
      alignSelf="stretch"
      background="#FFFFFF"
    >
      <Stack justify="flex-start" align="flex-start" spacing="16px">
        <Box>
          <Stack
            direction="row"
            justify="space-between"
            align="center"
            spacing="386px"
            width="1292.71px"
            maxWidth="100%"
          >
            <Box>
              <Text
                fontFamily="Outfit"
                lineHeight="1"
                fontWeight="black"
                fontSize="24px"
                textTransform="uppercase"
                color="#534C46"
              >
                Monthly sales
              </Text>
              <Text
                fontFamily="Outfit"
                lineHeight="1"
                fontWeight="medium"
                fontSize="24px"
                textTransform="capitalize"
                color="#6D635B"
              >
                Current year to last year comparison{' '}
              </Text>
            </Box>
            <Stack
              direction="row"
              justify="flex-end"
              align="flex-start"
              spacing="24px"
            >
              <Stack
                text="View Reports"
                property1="Default"
                direction="row"
                justify="flex-start"
                align="flex-start"
              >
                <Text
                  fontFamily="Outfit"
                  lineHeight="1.2"
                  fontWeight="medium"
                  fontSize="20px"
                  textTransform="capitalize"
                  color="#595959"
                >
                  Export Graph
                </Text>
              </Stack>
              <Stack
                text="View Reports"
                property1="Default"
                direction="row"
                justify="flex-start"
                align="flex-start"
              >
                <Text
                  fontFamily="Outfit"
                  lineHeight="1.2"
                  fontWeight="medium"
                  fontSize="20px"
                  textTransform="capitalize"
                  color="#595959"
                >
                  View Reports
                </Text>
              </Stack>
            </Stack>
          </Stack>
        </Box>
        <Stack
          direction="row"
          justify="flex-start"
          align="flex-start"
          spacing="32px"
        >
          <Stack direction="row" justify="flex-start" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1.33"
              fontWeight="regular"
              fontSize="18px"
              color="slate"
            >
              Current Year (2022){' '}
            </Text>
          </Stack>
          <Stack direction="row" justify="flex-start" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1.33"
              fontWeight="regular"
              fontSize="18px"
              color="#595959"
            >
              Last Year (2021)
            </Text>
          </Stack>
        </Stack>
      </Stack>
      <Box>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="20.53px"
          height="17.65px"
          textAlign="center"
        >
          Jan
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="26.21px"
          height="17.65px"
          textAlign="center"
        >
          Feb
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="33.37px"
          height="17.65px"
          textAlign="center"
        >
          Mar
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="32.99px"
          height="17.65px"
          textAlign="center"
        >
          Apr
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="34.13px"
          height="17.65px"
          textAlign="center"
        >
          May
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="35.26px"
          height="17.65px"
          textAlign="center"
        >
          Jun
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="31.87px"
          height="17.65px"
          textAlign="center"
        >
          Jul
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="42.05px"
          height="17.65px"
          textAlign="center"
        >
          Aug
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="38.63px"
          height="17.65px"
          textAlign="center"
        >
          Sep
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="30.73px"
          height="17.65px"
          textAlign="center"
        >
          Oct
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="40.92px"
          height="17.65px"
          textAlign="center"
        >
          Nov
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="46.57px"
          height="17.65px"
          textAlign="center"
        >
          Dec
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="7.51px"
          height="17.65px"
          textAlign="end"
        >
          0
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="49.79px"
          height="17.65px"
          textAlign="end"
        >
          $10,000
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="52.14px"
          height="17.65px"
          textAlign="end"
        >
          $20,000
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="52.14px"
          height="17.65px"
          textAlign="end"
        >
          $30,000
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="52.14px"
          height="17.65px"
          textAlign="end"
        >
          $40,000
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="52.14px"
          height="17.65px"
          textAlign="end"
        >
          $50,000
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="52.02px"
          height="17.65px"
          textAlign="end"
        >
          $60,000
        </Text>
        <Text
          fontFamily="Outfit"
          fontWeight="medium"
          fontSize="12px"
          color="#6D635B"
          width="52.13px"
          height="17.65px"
          textAlign="end"
        >
          $70,000
        </Text>
      </Box>
    </Stack>
    <Stack
      padding="32px"
      borderRadius="8px"
      justify="flex-start"
      align="flex-start"
      spacing="16px"
      borderColor="#6D635B"
      borderStartWidth="2px"
      borderEndWidth="2px"
      borderTopWidth="2px"
      borderBottomWidth="2px"
      alignSelf="stretch"
    >
      <Stack
        justify="flex-start"
        align="flex-start"
        spacing="16px"
        alignSelf="stretch"
      >
        <Stack
          direction="row"
          justify="space-between"
          align="flex-start"
          spacing="32px"
          alignSelf="stretch"
        >
          <Box>
            <Text
              fontFamily="Outfit"
              lineHeight="1"
              fontWeight="black"
              fontSize="24px"
              textTransform="uppercase"
              color="#534C46"
            >
              Monthly sales
            </Text>
            <Text
              fontFamily="Outfit"
              lineHeight="1"
              fontWeight="medium"
              fontSize="24px"
              color="#6D635B"
            >
              Total By Market
            </Text>
          </Box>
          <Stack
            direction="row"
            justify="flex-end"
            align="flex-start"
            spacing="24px"
          >
            <Stack
              text="View Reports"
              property1="Default"
              direction="row"
              justify="flex-start"
              align="flex-start"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.2"
                fontWeight="medium"
                fontSize="20px"
                textTransform="capitalize"
                color="#595959"
              >
                Export Graph
              </Text>
            </Stack>
            <Stack
              text="View Reports"
              property1="Default"
              direction="row"
              justify="flex-start"
              align="flex-start"
            >
              <Text
                fontFamily="Outfit"
                lineHeight="1.2"
                fontWeight="medium"
                fontSize="20px"
                textTransform="capitalize"
                color="#595959"
              >
                View Reports
              </Text>
            </Stack>
          </Stack>
        </Stack>
        <Stack
          direction="row"
          justify="flex-start"
          align="flex-start"
          spacing="32px"
        >
          <Stack direction="row" justify="flex-start" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1.33"
              fontWeight="regular"
              fontSize="18px"
              color="#595959"
            >
              Monroe Street
            </Text>
          </Stack>
          <Stack direction="row" justify="flex-start" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1.33"
              fontWeight="regular"
              fontSize="18px"
              color="#595959"
            >
              Columbia Heights [Wednesday]
            </Text>
          </Stack>
          <Stack direction="row" justify="flex-start" align="center">
            <Text
              fontFamily="Outfit"
              lineHeight="1.33"
              fontWeight="regular"
              fontSize="18px"
              color="#595959"
            >
              Columbia Heights [Saturday]
            </Text>
          </Stack>
        </Stack>
        <Box>
          <Box width="1268.34px" height="473.38px" maxWidth="100%" />
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="31.86px"
            height="12.41px"
            textAlign="center"
          >
            Jan
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="33.22px"
            height="12.41px"
            textAlign="center"
          >
            Feb
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="43.38px"
            height="12.41px"
            textAlign="center"
          >
            Mar
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="41.18px"
            height="12.41px"
            textAlign="center"
          >
            Apr
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="40.77px"
            height="12.41px"
            textAlign="center"
          >
            May
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="40.38px"
            height="12.41px"
            textAlign="center"
          >
            Jun
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="31.14px"
            height="12.41px"
            textAlign="center"
          >
            Jul
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="39.53px"
            height="12.41px"
            textAlign="center"
          >
            Aug
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="44.41px"
            height="12.41px"
            textAlign="center"
          >
            Sep
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="45.73px"
            height="12.41px"
            textAlign="center"
          >
            Oct
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="38.28px"
            height="12.41px"
            textAlign="center"
          >
            Nov
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="46.68px"
            height="12.41px"
            textAlign="center"
          >
            Dec
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="8.94px"
            height="12.41px"
            textAlign="end"
          >
            0
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="49.18px"
            height="12.41px"
            textAlign="end"
          >
            $10,000
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="52.53px"
            height="12.41px"
            textAlign="end"
          >
            $20,000
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="51.97px"
            height="12.41px"
            textAlign="end"
          >
            $30,000
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="51.97px"
            height="12.41px"
            textAlign="end"
          >
            $40,000
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="51.97px"
            height="12.41px"
            textAlign="end"
          >
            $50,000
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="52.53px"
            height="12.41px"
            textAlign="end"
          >
            $60,000
          </Text>
          <Text
            fontFamily="Outfit"
            fontWeight="medium"
            fontSize="12px"
            color="#6D635B"
            width="51.42px"
            height="12.41px"
            textAlign="end"
          >
            $70,000
          </Text>
        </Box>
      </Stack>
    </Stack>
  </Stack>
)
